# Generated by Django 5.0.3 on 2024-04-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_points_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='points',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='name',
            new_name='user',
        ),
    ]
