# Generated by Django 5.0.3 on 2024-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_pointstransfer_enter_points_to_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='enter_destination_username',
            field=models.CharField(max_length=50),
        ),
    ]
