# Generated by Django 5.0.3 on 2024-04-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_paymentrequest_enter_destination_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
