# Generated by Django 5.0.3 on 2024-04-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_paymentrequest_enter_destination_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='enter_destination_username',
            new_name='enter_destination_username_id',
        ),
    ]
