# Generated by Django 5.0.3 on 2024-04-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_rename_enter_destination_username_paymentrequest_enter_destination_username_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='enter_destination_username_id',
            new_name='enter_destination_username',
        ),
    ]
