# Generated by Django 5.0.3 on 2024-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_rename_enter_destination_username_id_paymentrequest_enter_destination_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='enter_destination_username',
            field=models.CharField(max_length=50),
        ),
    ]
