# Generated by Django 5.0.3 on 2024-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_paymentrequest_enter_destination_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
