# Generated by Django 5.0.3 on 2024-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='converted_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='converted_currency',
            field=models.CharField(default='GBP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(default='GBP', max_length=3),
            preserve_default=False,
        ),
    ]
