# Generated by Django 5.0.3 on 2024-05-01 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='enter_amount_to_request',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='enter_destination_username',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_payment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
