# Generated by Django 5.0.3 on 2024-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_rename_enter_amount_to_request_paymentrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
