# Generated by Django 5.0.3 on 2024-03-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_paymentrequest_status_transaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
