# Generated by Django 5.0.3 on 2024-05-10 10:44

from django.db import migrations
from django.contrib.auth.models import User


def create_admin_account(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    # check if the admin account already exists
    if not User.objects.filter(username='admin1').exists():
        # create a new admin user
        User.objects.create_superuser('admin1', 'admin1@example.com', 'admin1')


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_delete_paymentrequest'),
    ]

    operations = [
        migrations.RunPython(create_admin_account),
    ]
